### ISSUE TITLE
Ugly layout disposition with Xemlism GTK Theme

### ISSUE THREAD

**Issue by SalahAdDin** [xenlism/minimalism#16]
I love this theme, i couldn't found other like this, but it have some problems.

In this case, while `shell` theme is precious, `GTK` theme is very, very ugly:
![seleccion_001](https://cloud.githubusercontent.com/assets/5034215/26002045/07b0839a-3737-11e7-8015-1d7eb9b30a9a.png)

How can we solve it?

**Comment by ViniciusBRodrigues** [comment]
I also had this problem in gnome 3.20.2
