### ISSUE TITLE
Top panel and it's elements are black in fedora.

### ISSUE THREAD

**Issue by 0xsanjayprajapat** [xenlism/minimalism#18]
In your screenshots top panel and it's elements are also changed, but in my system (Fedora 28) they look like default theme.

![screenshot from 2018-05-11 19-20-16](https://user-images.githubusercontent.com/18235954/39928270-8810ccb8-5552-11e8-8ba2-a5710e0a5ecd.png)

![screenshot from 2018-05-11 19-23-36](https://user-images.githubusercontent.com/18235954/39928272-8848bc0e-5552-11e8-9eef-017573b34676.png)

**Comment by xenlism** [comment]
How you install xenlism minimalism theme? Last version on github?

Nattapong Pullkhow <ixenatt@gmail.com>

เมื่อ 11 พ.ค. 2561 เวลา 21:07 Sanjay Prajapat <notifications@github.com> เขียน:

**Comment by 0xsanjayprajapat** [comment]
I installed it yesterday using git, then it should be latest version on github. 

cd /tmp;git clone https://github.com/xenlism/minimalism.git;bash /tmp/minimalism/INSTALL/offine.install;

**Comment by xenlism** [comment]
I will fix it soon ASAP.my machine don't have fedora. 

Nattapong Pullkhow <ixenatt@gmail.com>

เมื่อ 12 พ.ค. 2561 เวลา 03:42 Sanjay Prajapat <notifications@github.com> เขียน:

**Comment by 0xsanjayprajapat** [comment]
when i switch to "GNOME classic" at login screen, then it works but not working in GNOME (Wayland and Xorg).

**Comment by xenlism** [comment]
Are you sure?
![screenshot from 2018-05-12 14-49-27](https://user-images.githubusercontent.com/13846221/39955040-b6355dec-55f3-11e8-9fe0-c81f9d03169d.png)
This Fedora 28 , Gnome-shell 3.28.1

**Comment by 0xsanjayprajapat** [comment]
I just checked this theme in other system too, but the result was same.

![screenshot from 2018-05-13 03-15-09](https://user-images.githubusercontent.com/18235954/39961818-b5d0770c-565b-11e8-8ecb-c49430159f3b.png)

**Comment by xenlism** [comment]
Are you kidding me? your gnome-shell theme was adwaita.
![39961818-b5d0770c-565b-11e8-8ecb-c49430159f3b copy](https://user-images.githubusercontent.com/13846221/39962874-2748e4c6-5686-11e8-826f-708f67599620.png)
