### ISSUE TITLE
E: The repository 'http://ppa.launchpad.net/xenatt/xenlism/ubuntu cosmic Release' does not have a Release file.

### ISSUE THREAD

**Issue by jchannon** [xenlism/minimalism#19]
Trying to install on ubuntu 18.10 but getting this error following the README instructions.

**Comment by xenlism** [comment]
Not support now, Fix soon.

ส่งจาก iPad ของฉัน

เมื่อ 6 พ.ย. 2561 เวลา 03:50 Jonathan Channon <notifications@github.com> เขียน:

**Comment by xenlism** [comment]
Please check it out now cosmic is pending on launchpad.net

**Comment by jchannon** [comment]
Thanks
