### ISSUE TITLE
Bad color on activity menu

### ISSUE THREAD

**Issue by dwlsalmeida** [xenlism/minimalism#2]
I'm using GNOME 3.18, and currently it's hard to read the tooltip beneath each app in the activity menu..screenshot attached
![screenshot from 2015-10-13 15-21-52](https://cloud.githubusercontent.com/assets/11738710/10464114/79ca0892-71be-11e5-9c19-b65fa6a4f8c6.png)

**Comment by wbtuomela** [comment]
Fixed in my PR (https://github.com/xenlism/minimalism/pull/8)

![activties-overview-hover](https://cloud.githubusercontent.com/assets/205437/12662977/cc01e4c2-c5d8-11e5-8fea-f4523a60bbd1.png)
