### ISSUE TITLE
Loading icon is broken

### ISSUE THREAD

**Issue by FBemf** [xenlism/minimalism#22]
The buggy file is `gnome-shell/common-assets-misc/process-working.svg`

When a new window is loading, instead of the spinning circle, it flickers through different angles and slices of the circle, as if the sprite sheet is misaligned. I fixed it on my machine by swapping in the `process-working.svg` file from [this theme](https://github.com/EliverLara/Ant), which works as expected.

**Comment by xenlism** [comment]
Yes,

**Comment by davidbepo** [comment]
i actually find this funny, so i havent bothered looking for a solution

**Comment by xenlism** [comment]
I will fix soon.

ในวันที่ พฤ. 14 มี.ค. 2019 08:21 น. davidbepo <notifications@github.com>
เขียนว่า:
