### ISSUE TITLE
issues with gnome shell 3.34

### ISSUE THREAD

**Issue by davidbepo** [xenlism/minimalism#26]
![Captura de pantalla de 2019-09-24 15-51-50](https://user-images.githubusercontent.com/18667173/65517599-477fa180-dee3-11e9-9fcf-6fb98e815ae1.png)

this screenshot has most of them

**Comment by xenlism** [comment]
I'm working now.

ในวันที่ อ. 24 ก.ย. 2019 20:53 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
okay, thanks
also could you release a new version on the repo once the issues are fixed?

**Comment by xenlism** [comment]
I need time for fix this problem.

ในวันที่ อ. 24 ก.ย. 2019 21:31 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
okay, do you want more screenshots of issues?

**Comment by xenlism** [comment]
Yes,Please.

ในวันที่ พ. 25 ก.ย. 2019 03:58 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
the player notification has ureadable text and invisible buttons
![Captura de pantalla de 2019-09-25 00-49-10](https://user-images.githubusercontent.com/18667173/65556052-96065d80-df2e-11e9-9fbd-602f12acdbe3.png)
![Captura de pantalla de 2019-09-25 00-49-06](https://user-images.githubusercontent.com/18667173/65556054-969ef400-df2e-11e9-95f2-2ef102f85aa6.png)
im pretty sure volume slider shouldnt look like this
![Captura de pantalla de 2019-09-25 00-52-34](https://user-images.githubusercontent.com/18667173/65556118-d534ae80-df2e-11e9-9c50-12dfafd5b46a.png)

**Comment by davidbepo** [comment]
the notification text is illegible
![Captura de pantalla de 2019-09-25 00-58-40](https://user-images.githubusercontent.com/18667173/65556422-eb8f3a00-df2f-11e9-8543-631558bb0da7.png)

**Comment by xenlism** [comment]
I'm commited new update to github.

**Comment by davidbepo** [comment]
i tried this update and while it fixes some of the issues it doesnt fix all and it also introduces new ones :(

**Comment by davidbepo** [comment]
the text font and the dock look worse than before, also icons on the top bar are too close:
![Captura de pantalla de 2019-09-25 11-32-44](https://user-images.githubusercontent.com/18667173/65588747-59ffe680-df88-11e9-8b77-eeff5b88993b.png)
there is till too much space right to the app name, and the player notification still has invisible buttons:
![Captura de pantalla de 2019-09-25 11-37-41](https://user-images.githubusercontent.com/18667173/65589288-18237000-df89-11e9-9044-e5091490ca43.png)
this still selects in black:
![Captura de pantalla de 2019-09-25 11-39-41](https://user-images.githubusercontent.com/18667173/65589392-3d17e300-df89-11e9-8f40-d9072b0dabb8.png)

**Comment by davidbepo** [comment]
there is also one thing that happens in 3.34, the backgrounds dims more than on previous versions on the overview and when a shell popup appears
not sure if a bug, but was better before

**Comment by xenlism** [comment]
I use Arch Linux.Dash to Dock not work now.
Please wait for dash to Dock update.

ในวันที่ พ. 25 ก.ย. 2019 16:42 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
> I use Arch Linux.Dash to Dock not work now. Please wait for dash to Dock update

i manually installed the git version which works on 3.34
theme pre-update it looked good and theme post-update bad

**Comment by xenlism** [comment]
Thank for your information.

ในวันที่ พ. 25 ก.ย. 2019 16:52 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by xenlism** [comment]
Please Try new update
[image: Screenshot from 2019-09-25 20-14-44.png]

ในวันที่ พ. 25 ก.ย. 2019 เวลา 16:59 Nattapong Pullkhow <ixenatt@gmail.com>
เขียนว่า:

**Comment by davidbepo** [comment]
this new update fixes most issues but it also introduces new ones, mainly the top bar is now tiny and the font is tiny too, the system icons look weird, also some things are now selected in white which didn't happen before
![Captura de pantalla de 2019-09-25 15-44-50](https://user-images.githubusercontent.com/18667173/65606764-ba544f80-dfab-11e9-9ad2-75f6c82045f8.png)
the notifications are fixed
the extra space right to the app name and too dark background dimming are not, but it happens with all themes so this might be a gnome-shell issue and not this theme
minor thing but the week squares are now grey instead of blue
![Captura de pantalla de 2019-09-25 15-54-09](https://user-images.githubusercontent.com/18667173/65607450-df958d80-dfac-11e9-81e4-da1ab5794e9d.png)

i have a suggestion too: couldn't you use system font or the same as the default theme does? that works pretty well

**Comment by davidbepo** [comment]
i picked a change and i dont know if its intentional, shell popup buttons are now white (they where dark before)
![Captura de pantalla de 2019-09-25 15-59-30](https://user-images.githubusercontent.com/18667173/65607910-9bef5380-dfad-11e9-8c4c-ddf1367b07e6.png)

**Comment by xenlism** [comment]
Yes, I working on adwaita 3.34.

ในวันที่ พ. 25 ก.ย. 2019 21:00 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
i picked something more, the volume popup

![Captura de pantalla de 2019-09-25 16-54-37](https://user-images.githubusercontent.com/18667173/65613051-9dbd1500-dfb5-11e9-82b9-cab3dc80c548.png)

**Comment by davidbepo** [comment]
any progress?

**Comment by xenlism** [comment]
Not update in few days.

ในวันที่ พฤ. 26 ก.ย. 2019 20:38 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by xenlism** [comment]
I already update new version now.

ในวันที่ พฤ. 26 ก.ย. 2019 23:33 น. Nattapong Pullkhow <ixenatt@gmail.com>
เขียนว่า:

**Comment by davidbepo** [comment]
i had a big problem and downgraded to gnome 3.32 but i can test there
3.34 will require making a VM and will take some time...

**Comment by davidbepo** [comment]
since im on 3.32 i can test the before and after easily
before:
![Captura de pantalla de 2019-09-28 22-14-10](https://user-images.githubusercontent.com/18667173/65821995-66609980-e23d-11e9-95b7-afe3d1441023.png)
after
![Captura de pantalla de 2019-09-28 22-13-34](https://user-images.githubusercontent.com/18667173/65821993-606ab880-e23d-11e9-802b-7d72e4eb06de.png)

**Comment by davidbepo** [comment]
the new version still has a bunch of issues :(

**Comment by xenlism** [comment]
I'm test on gnome 3.34

ในวันที่ อา. 29 ก.ย. 2019 03:15 น. davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
i made the vm with gnome 3.34 and can share some screenshots, but in the new theme version what is wrong in 3.32 is also on 3.34
small top bar, font, and weird icons:
![Captura de pantalla de 2019-09-29 16-55-20](https://user-images.githubusercontent.com/18667173/65834360-62368980-e2da-11e9-9299-28488419bf35.png)
the volume slider has no "ball", and also has same color for over-volume
![Captura de pantalla de 2019-09-29 16-55-38](https://user-images.githubusercontent.com/18667173/65834386-99a53600-e2da-11e9-8eb6-ff691d7ba1b4.png)
hover in shell buttons is still weird:
![Captura de pantalla de 2019-09-29 16-55-40](https://user-images.githubusercontent.com/18667173/65834410-c8bba780-e2da-11e9-8334-fc9550361a72.png)

**Comment by xenlism** [comment]
[image: Screenshot from 2019-09-30 08-31-11.png]
[image: Screenshot from 2019-09-30 08-31-00.png]

ในวันที่ อา. 29 ก.ย. 2019 เวลา 22:02 davidbepo <notifications@github.com>
เขียนว่า:

**Comment by davidbepo** [comment]
?
your comment doesnt show images

**Comment by davidbepo** [comment]
any update?
i got 3.34 running again on my main system so i can test properly

**Comment by davidbepo** [comment]
@xenlism ping
