### ISSUE TITLE
Ugly sidebar on Nautilus

### ISSUE THREAD

**Issue by Tmbao** [xenlism/minimalism#3]
I'm using fedora 23 beta with gnome shell 3.18. After installing minimalism, I got a ugly nautilus sidebar. Hope that It will be fixed soon.

![screenshot from 2015-10-17 07-57-25](https://cloud.githubusercontent.com/assets/7766181/10556080/bab75286-74a4-11e5-8adc-7a0177f87d48.png)

**Comment by maltesa** [comment]
I have the same problem. I fixed the icon padding problem by adding this:

```
NautilusWindow .sidebar-icon {
  padding-left: 5px;
  padding-right: 10px;
  padding-bottom: 3px;
}
```

to /usr/share/themes/Xenilism-Minimalism/gtk-3.0/gtk-contained.css

**Comment by SalahAdDin** [comment]
@maltesa i have the same problem and i will put here but here can report it. Which is the standard for the padding?
![seleccion_065](https://cloud.githubusercontent.com/assets/5034215/12862123/8589561a-cc36-11e5-898c-f23123d6e7bd.png)

**Comment by SalahAdDin** [comment]
Ok, i fixed this but, only work in main nautilus explorer, in other explorer doesn't works:
![area de trabajo 1_070](https://cloud.githubusercontent.com/assets/5034215/12864055/adc990b4-cc4e-11e5-86bb-96c5a9e094a8.png)
