### ISSUE TITLE
Ugly run-application 

### ISSUE THREAD

**Issue by Tmbao** [xenlism/minimalism#4]
I'm using fedora 23 beta with gnome shell 3.18. After installing minimalism, I got a ugly run-application 
(alt+f2). Hope that it will be fixed soon.

![screenshot from 2015-10-17 08-09-28](https://cloud.githubusercontent.com/assets/7766181/10556165/86959588-74a6-11e5-86f1-5cae59350209.png)

**Comment by dwlsalmeida** [comment]
Same on arch + gnome 3.18

**Comment by wbtuomela** [comment]
I fixed this with my PR (https://github.com/xenlism/minimalism/pull/7).

![run-dialog](https://cloud.githubusercontent.com/assets/205437/12661318/bbd6ecc4-c5cd-11e5-8719-666726cf64d6.png)
