### ISSUE TITLE
Nautilus sidebar issues with overall dark theme

### ISSUE THREAD

**Issue by magdeoz** [xenlism/minimalism#5]
GNOME 3.18 with the overall dark theme is too ugly and almost illegible.
GNOME 3.16 did not have that problem
![captura de pantalla de 2015-10-20 18-01-50](https://cloud.githubusercontent.com/assets/10053172/10623445/b7091338-7754-11e5-9c9a-c0ff30740f3d.png)

**Comment by riesinger** [comment]
+1 for this issue, I did not have this theme on 3.16, but that white border is awful...
I also dug arround in the theme file, but I do not know enough to fix it

**Comment by riesinger** [comment]
See my PR [#6](https://github.com/xenlism/minimalism/pull/6). I fixed it there.

EDIT: when maximizing the window, the white borders still apear (no idea why)
